language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'

addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube: true

script: 
  - phpunit testes/Test.php
  - sonar-scanner -Dsonar.login=b1389d4ef817a6c1b0f6049dcf383ede3b6997a5


notifications:
  slack: evasao:LbVZOEbgooG84HhpV7HQEahl
  email: false
